version: "3.5"

services:
  roach:
    image: cockroachdb/cockroach:latest
    networks:
      - backend
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure

    volumes:
      - ./db/cockroach:/cockroach/cockroach-data

networks:
  backend:
